************* Module src.unit_test_generator
unit_test_generator.py:771:0: C0301: Line too long (120/100) (line-too-long)
unit_test_generator.py:775:0: C0301: Line too long (112/100) (line-too-long)
unit_test_generator.py:1166:0: C0301: Line too long (126/100) (line-too-long)
unit_test_generator.py:1840:0: C0301: Line too long (152/100) (line-too-long)
unit_test_generator.py:1843:0: C0301: Line too long (112/100) (line-too-long)
unit_test_generator.py:1996:0: C0301: Line too long (132/100) (line-too-long)
unit_test_generator.py:2043:0: C0301: Line too long (124/100) (line-too-long)
unit_test_generator.py:2054:0: C0301: Line too long (124/100) (line-too-long)
unit_test_generator.py:1:0: C0302: Too many lines in module (2266/1000) (too-many-lines)
unit_test_generator.py:988:5: W0511: TODO Add the function file and function name (fixme)
unit_test_generator.py:998:9: W0511: TODO Return the cached result to save a lot of time! (fixme)
unit_test_generator.py:1837:9: W0511: TODO Why is this_state.args_after sometimes a tuple?? (fixme)
unit_test_generator.py:2039:13: W0511: TODO (fixme)
unit_test_generator.py:2050:13: W0511: TODO (fixme)
unit_test_generator.py:219:4: R0914: Too many local variables (16/15) (too-many-locals)
unit_test_generator.py:722:0: R0902: Too many instance attributes (10/7) (too-many-instance-attributes)
unit_test_generator.py:726:4: R0913: Too many arguments (6/5) (too-many-arguments)
unit_test_generator.py:766:4: R0914: Too many local variables (16/15) (too-many-locals)
unit_test_generator.py:766:4: R0912: Too many branches (27/12) (too-many-branches)
unit_test_generator.py:766:4: R0915: Too many statements (73/50) (too-many-statements)
unit_test_generator.py:1914:49: W0123: Use of eval (eval-used)
unit_test_generator.py:2031:34: W0123: Use of eval (eval-used)

------------------------------------------------------------------
Your code has been rated at 9.83/10 (previous run: 9.82/10, +0.01)

