************* Module src.unit_test_generator
unit_test_generator.py:775:0: C0301: Line too long (128/100) (line-too-long)
unit_test_generator.py:1:0: C0302: Too many lines in module (1860/1000) (too-many-lines)
unit_test_generator.py:327:9: W0511: TODO add a "update_types_in_use" method (fixme)
unit_test_generator.py:422:17: W0511: TODO try/catch/raise exception (fixme)
unit_test_generator.py:459:21: W0511: TODO try/catch/raise exception (fixme)
unit_test_generator.py:490:21: W0511: TODO try/catch/raise exception (fixme)
unit_test_generator.py:499:21: W0511: TODO try/catch/raise exception (fixme)
unit_test_generator.py:983:5: W0511: TODO remove these assserts and the hash_keys set (fixme)
unit_test_generator.py:989:5: W0511: TODO remove this deepcopy (fixme)
unit_test_generator.py:1059:5: W0511: TODO: Find a better way to do this than a str compare! (fixme)
unit_test_generator.py:1088:9: W0511: TODO: Determine if there's ever more than one leading space (fixme)
unit_test_generator.py:1181:13: W0511: TODO: This is (fixme)
unit_test_generator.py:1317:9: W0511: TODO Fix bug here where function_metadata.coverage_io dictionaries (fixme)
unit_test_generator.py:1323:9: W0511: TODO The code below is likely unnecessary now (fixme)
unit_test_generator.py:109:4: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)
unit_test_generator.py:346:15: E1120: No value for argument 'obj' in function call (no-value-for-parameter)
unit_test_generator.py:553:12: W0719: Raising too general exception: Exception (broad-exception-raised)
unit_test_generator.py:634:0: W1113: Keyword argument before variable positional arguments list in the definition of do_the_decorator_thing function (keyword-arg-before-vararg)
unit_test_generator.py:723:19: W0718: Catching too general exception Exception (broad-exception-caught)
unit_test_generator.py:765:20: W0123: Use of eval (eval-used)
unit_test_generator.py:831:11: W0718: Catching too general exception Exception (broad-exception-caught)
unit_test_generator.py:864:15: W0718: Catching too general exception Exception (broad-exception-caught)
unit_test_generator.py:634:0: R0912: Too many branches (53/12) (too-many-branches)

------------------------------------------------------------------
Your code has been rated at 9.73/10 (previous run: 9.72/10, +0.01)

